- task: AzireCLI@2
  displayname: Azure CLI
  inputs:
    azureSubscription: fcodocker
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
